- name: Creates directory /home/volk/git/whir
  remote_user: volk
  file:
          path: /home/volk/git/whir
          state: directory

- name: Cloning whir app project
  remote_user: volk
  command: git clone http://10.5.33.229:1180/root/whir.git /home/volk/git/whir
  retries: 3
  delay: 3
  until: git_clone.rc == 0
  register: git_clone
  ignore_errors: True

- name: Pull if git clone falied
  remote_user: volk
  command: git pull http://10.5.33.229:1180/root/whir.git
  args:
          chdir: /home/volk/git/whir
  when: git_clone is failed

- name: Checkout master branch
  remote_user: volk
  command: git checkout master
  args:
          chdir: /home/volk/git/whir

- name: build docker whir-app image
  command: docker build . -t docker.ask4ua.com/whir-app -f docker/images/app/Dockerfile
  args:
          chdir: /home/volk/git/whir

- name: build docker whir-db image
  command: docker build . -t docker.ask4ua.com/whir-db -f docker/images/db/Dockerfile
  args:
          chdir: /home/volk/git/whir

- name: Swarm Init
  command: docker swarm init
  register: swarm_init_result
  ignore_errors: True

- name: create secrets
  remote_user: volk
  command: bash docker/usefulscripts.sh
  args:
          chdir: /home/volk/git/whir

- name: start Whir stack
  command: docker stack deploy whir -c docker/stack/docker-compose.yml
  args:
          chdir: /home/volk/git/whir