files=[
['Mark Twain','The $30,000 Bequest And Other Stories','/data/SRC/Twain, Mark - $30,000 Bequest And Other Stories, The.txt'],
['Mark Twain','1601','/data/SRC/Twain, Mark - 1601.txt'],
['Mark Twain','The Adventures of Huckleberry Finn','/data/SRC/Twain, Mark - Adventures of Huckleberry Finn, The.txt'],
['Mark Twain','The Adventures of Tom Sawyer','/data/SRC/Twain, Mark - Adventures of Tom Sawyer, The.txt'],
['Mark Twain','Alonzo Fitz And Other Stories','/data/SRC/Twain, Mark - Alonzo Fitz And Other Stories.txt'],
['Mark Twain','The American Claimant','/data/SRC/Twain, Mark - American Claimant, The.txt'],
['Mark Twain','Captain Stormfield\'s Visit To Heaven','/data/SRC/Twain, Mark - Captain Stormfield\'s Visit To Heaven.txt'],
['Mark Twain','Carnival of Crime in CT','/data/SRC/Twain, Mark - Carnival of Crime in CT.txt'],
['Mark Twain','Christian Science','/data/SRC/Twain, Mark - Christian Science.txt'],
['Mark Twain','Complete Letters Of Mark Twain','/data/SRC/Twain, Mark - Complete Letters Of Mark Twain.txt'],
['Mark Twain','A Connecticut Yankee in King Arthur\'s Court','/data/SRC/Twain, Mark - Connecticut Yankee in King Arthur\'s Court, A.txt'],
['Mark Twain','Curious Republic Of Gondour, And Other Curious Whimsical Sketches','/data/SRC/Twain, Mark - Curious Republic Of Gondour, And Other Curious Whimsical Sketches.txt'],
['Mark Twain','A Dog\'s Tale','/data/SRC/Twain, Mark - Dog\'s Tale, A.txt'],
['Mark Twain','A Double Barrelled Detective Story','/data/SRC/Twain, Mark - Double Barrelled Detective Story , A.txt'],
['Mark Twain','Extracts From Adam\'s Diary','/data/SRC/Twain, Mark - Extracts From Adam\'s Diary.txt'],
['Mark Twain','Fenimore Cooper\'s Literary Offences','/data/SRC/Twain, Mark - Fenimore Cooper\'s Literary Offences.txt'],
['Mark Twain','Following The Equator','/data/SRC/Twain, Mark - Following The Equator.txt'],
['Mark Twain','Gilded Age, The; a tale of today','/data/SRC/Twain, Mark - Gilded Age, The; a tale of today.txt'],
['Mark Twain','Goldsmith\'s Friend Abroad Again','/data/SRC/Twain, Mark - Goldsmith\'s Friend Abroad Again.txt'],
['Mark Twain','A Horse\'s Tale','/data/SRC/Twain, Mark - Horse\'s Tale, A.txt'],
['Mark Twain','How To Tell A Story And Other Essays','/data/SRC/Twain, Mark - How To Tell A Story And Other Essays.txt'],
['Mark Twain','In Defence Of Harriet Shelley','/data/SRC/Twain, Mark - In Defence Of Harriet Shelley.txt'],
['Mark Twain','Innocents Abroad','/data/SRC/Twain, Mark - Innocents Abroad.txt'],
['Mark Twain','Is Shakespeare Dead - From my autobiography','/data/SRC/Twain, Mark - Is Shakespeare Dead - From my autobiography.txt'],
['Mark Twain','Life on the Mississippi','/data/SRC/Twain, Mark - Life on the Mississippi .txt'],
['Mark Twain','The Man That Corrupted Hadleyburg','/data/SRC/Twain, Mark - Man That Corrupted Hadleyburg, The.txt'],
['Mark Twain','Mark Twain\'s Burlesque Autobiography','/data/SRC/Twain, Mark - Mark Twain\'s Burlesque Autobiography.txt'],
['Mark Twain','Mark Twain\'s Speeches','/data/SRC/Twain, Mark - Mark Twain\'s Speeches.txt'],
['Mark Twain','Mark Twain\'s A Biography','/data/SRC/Twain, Mark - Mark Twain\'s A Biography.txt'],
['Mark Twain','The Mysterious Stranger','/data/SRC/Twain, Mark - Mysterious Stranger, The.txt'],
['Mark Twain','On The Decay Of The Art Of Lying','/data/SRC/Twain, Mark - On The Decay Of The Art Of Lying.txt'],
['Mark Twain','Personal Recollections Of Joan Of Arc vol 1','/data/SRC/Twain, Mark - Personal Recollections Of Joan Of Arc vol 1.txt'],
['Mark Twain','Personal Recollections Of Joan Of Arc vol 2','/data/SRC/Twain, Mark - Personal Recollections Of Joan Of Arc vol 2.txt'],
['Mark Twain','The Prince and the Pauper','/data/SRC/Twain, Mark - Prince and the Pauper, The.txt'],
['Mark Twain','Pudd\'n\'head Wilson','/data/SRC/Twain, Mark - Pudd\'n\'head Wilson.txt'],
['Mark Twain','Roughing It','/data/SRC/Twain, Mark - Roughing It.txt'],
['Mark Twain','Sketches New And Old','/data/SRC/Twain, Mark - Sketches New And Old.txt'],
['Mark Twain','Some Rambling Notes Of An Idle Excursion','/data/SRC/Twain, Mark - Some Rambling Notes Of An Idle Excursion.txt'],
['Mark Twain','Stolen White Elephant','/data/SRC/Twain, Mark - Stolen White Elephant.txt'],
['Mark Twain','Those Extraordinary Twins','/data/SRC/Twain, Mark - Those Extraordinary Twins.txt'],
['Mark Twain','Tom Sawyer, Abroad','/data/SRC/Twain, Mark - Tom Sawyer, Abroad.txt'],
['Mark Twain','Tom Sawyer, Detective','/data/SRC/Twain, Mark - Tom Sawyer, Detective.txt'],
['Mark Twain','Tramp Abroad, A','/data/SRC/Twain, Mark - Tramp Abroad, A.txt'],
['Mark Twain','What Is Man - and Other Essays','/data/SRC/Twain, Mark - What Is Man - and Other Essays.txt'],
['Mark Twain','What Paul Bourget Thinks Of Us','/data/SRC/Twain, Mark - What Paul Bourget Thinks Of Us.txt']

      ]
