 - name: Check update is not locked
   remote_user: root
   action: apt update_cache=yes
   register: apt_lock
   ignore_errors: True

 - name: Update is locked - reboot the host
   remote_user: root
   action: reboot
   when: apt_lock is failed

 - name: Insatll docker installation dependenices
   remote_user: root
   action: apt name={{item}} state=installed
   with_items:
           - curl

 - name: Installs docker
   remote_user: root
   shell: curl -fsSL https://get.docker.com | sh -

 - name: Installs docker user
   remote_user: root
   command: adduser volk docker
