          - name: shut vhost "{{ item }}" in virsh
            remote_user: root
            become: yes
            become_method: sudo
            command: virsh shutdown {{item}}
            loop:
                - whir
                - elk
            ignore_errors: True

          - name: copy default image for {{item}}
            remote_user: root
            become: yes
            become_method: sudo
            command: rsync -auv /mnt/4T/virsh/images/u1804_64.qcow2 /var/lib/virsh/u1804_64_{{item}}.qcow2.wait
            loop:
                - whir
                - elk
                
          - name: stop virsh {{item}}
            remote_user: root
            become: yes
            become_method: sudo
            command: virsh destroy {{item}}
            loop:
                - whir
                - elk
            ignore_errors: True

          - name: remove old image for {{item}}
            remote_user: root
            become: yes
            become_method: sudo
            command: rm -rf u1804_64_{{item}}.qcow2
            args:
                    chdir: /var/lib/virsh/
            loop:
                - whir
                - elk


          - name: remove old image for {{item}}
            remote_user: root
            become: yes
            become_method: sudo
            command: rm -rf u1804_64_{{item}}.qcow2
            args:
                    chdir: /var/lib/virsh/
            loop:
                - whir
                - elk


          - name: rename image for {{item}}
            remote_user: root
            become: yes
            become_method: sudo
            command: mv u1804_64_{{item}}.qcow2.wait u1804_64_{{item}}.qcow2
            args:
                    chdir: /var/lib/virsh/
            loop:
                - whir
                - elk

          - name: start {{item}}
            remote_user: root
            become: yes
            become_method: sudo
            command: virsh start {{item}}
            loop:
                - whir
                - elk
          - name: give vhosts time to start
            pause: minutes=1
