- hosts: whirs
  tasks:
          - name: Creates directory /home/volk/git/whir
            file:
                    path: /home/volk/git/whir
                    state: directory
          - name: Cloning whir app project
            git: clone=yes repo=http://10.5.33.229:1180/root/whir.git dest=/home/volk/git/whir
          - name: build docker file
            shell: cd /home/volk/git/whir && docker build . -t docker.ask4ua.com/whir-app -f docker/images/app/Dockerfile && docker build . -t docker.ask4ua.com/whir-db -f docker/images/db/Dockerfile
          - name: create stack
            shell: docker swarm init
          - name: start stack
            shell: cd /home/volk/git/whir && docker stack deploy whir -c docker/stack/docker-compose.yml
