- name: Install prereqizites
  remote_user: root
  - hosts: elks
       roles: docker

- name: Install Appplications
 - hosts: elks
   roles: install_elk

 - hosts: whirs
   roles:
    - remove_whir
    - install_logspout
    - install_whir

