- name: Installing docker where it is needed
  hosts: elks
  remote_user: root
  roles: install_docker

- name: Installing ELK and whir where it is needed
 - hosts: elks
    roles:
      - install_elk

 - hosts: whirs
   roles:
    - remove_whir
    - install_logspout
    - install_whir
