apiVersion: v1
kind: Pod
metadata:
	labels:
		name: whir
	name: whir
spec:
	containers:
	- name: data
      volumeMounts:
      - name: data_vol
        mountPath: /data
      image: docker.ask4ua.com/whir-app
      command: "/bin/bash /app/clone.sh"
	- name: parser
      env:
      - name: WHIR_DB_USER
        value: whir
      - name: WHIR_DB_NAME
        value: whir
      - name: WHIR_DB_PASSWORD_FILE
        value: /run/secrets/whir_db_password
      - name: WHIR_DB_HOST
        value: postgres
      volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/run/secrets"
      - name: data_vol
        mountPath: /data
      image: docker.ask4ua.com/whir-app
      command: "/usr/bin/python3 parser.py"
    - name: decomposer
      env:
      - name: WHIR_DB_USER
        value: whir
      - name: WHIR_DB_NAME
        value: whir
      - name: WHIR_DB_PASSWORD_FILE
        value: /run/secrets/whir_db_password
      - name: WHIR_DB_HOST
        value: postgres
      volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/run/secrets"
      - name: data_vol
        mountPath: /data
      image: docker.ask4ua.com/whir-app
      command: "/usr/bin/python3 decomposer.py"
    - name: postgres
      env:
      - name: WHIR_DB_USER
        value: whir
      - name: WHIR_DB_NAME
        value: whir
      - name: WHIR_DB_PASSWORD_FILE
        value: /run/secrets/whir_db_password
      - name: POSTGRES_ROOT_PASSWORD_FILE
        value: /run/secrets/root_db_password
      volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/run/secrets"
      - name: postgres_vol
        mountPath: /var/lib/postgresql/data
      image: docker.ask4ua.com/whir-db
      ports:
      - containerPort: 5432
        hostPort: 5432