apiVersion: v1
kind: Pod
metadata:
  labels:
    name: whir-data
  name: whir-data
spec:
  containers:
  - name: data
    image: docker.ask4ua.com/whir-data
    volumeMounts:
    - name: data-vol
      mountPath: /data
  - name: parser
    env:
    - name: WHIR_DB_USER
      valueFrom:
        secretKeyRef:
          name: whir-pass
          key: whir_db_user
    - name: WHIR_DB_NAME
      valueFrom:
        secretKeyRef:
          name: whir-pass
          key: whir_db
    - name: WHIR_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: whir-pass
          key: whir_db_password
    - name: WHIR_DB_HOST
      value: whir-db
    volumeMounts:
    - name: data-vol
      mountPath: /data
    image: docker.ask4ua.com/whir-parser
  - name: decomposer
    env:
    - name: WHIR_DB_USER
      valueFrom:
        secretKeyRef:
          name: whir-pass
          key: whir_db_user
    - name: WHIR_DB_NAME
      valueFrom:
        secretKeyRef:
          name: whir-pass
          key: whir_db
    - name: WHIR_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: whir-pass
          key: whir_db_password
    - name: WHIR_DB_HOST
      value: whir-db
    volumeMounts:
    - name: data-vol
      mountPath: /data
    image: docker.ask4ua.com/whir-decomposer
  volumes:
  - name: secrets-vol
    secret:
      secretName: whir-pass
  - name: data-vol