apiVersion: v1
kind: Pod
metadata:
  labels:
    name: elk
  name: elk
spec:
  containers:
  - name: es
    image: ehazlett/elasticsearch
    ports:
    - containerPort: 9200
      hostPort: 9200
    - containerPort: 9300
      hostPort: 9300

  - name: kibana
    image: ehazlett/kibana
    ports:
    - containerPort: 80
      hostPort: 80

  - name: logstash
    image: ehazlett/logstash
    ports:
    - containerPort: 5000
      hostPort: 5000


  - name: es
    image: docker.ask4ua.com/whir-data
    volumeMounts:
    - name: data-vol
      mountPath: /data


  - name: parser
    env:
    - name: WHIR_DB_USER
      valueFrom:
        secretKeyRef:
          name: whir-pass
          key: whir_db_user
    - name: WHIR_DB_NAME
      valueFrom:
        secretKeyRef:
          name: whir-pass
          key: whir_db
    - name: WHIR_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: whir-pass
          key: whir_db_password
    - name: WHIR_DB_HOST
      value: 127.0.0.1
    volumeMounts:
    - name: data-vol
      mountPath: /data
    image: docker.ask4ua.com/whir-parser

  - name: decomposer
    env:
    - name: WHIR_DB_USER
      valueFrom:
        secretKeyRef:
          name: whir-pass
          key: whir_db_user
    - name: WHIR_DB_NAME
      valueFrom:
        secretKeyRef:
          name: whir-pass
          key: whir_db
    - name: WHIR_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: whir-pass
          key: whir_db_password
    - name: WHIR_DB_HOST
      value: 127.0.0.1
    volumeMounts:
    - name: data-vol
      mountPath: /data
    image: docker.ask4ua.com/whir-decomposer

