apiVersion: v1
kind: ReplicationController
metadata:
  name: whir-db
spec:
  replicas: 1
  selector:
    tier: whir-db
  template:
    metadata:
      labels:
        tier: whir-db
    spec:
      nodeSelector:
        ramsize: 4plus
      containers:
      - name: postgres
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: whir-pass
              key: whir_db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: whir-pass
              key: whir_db_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: whir-pass
              key: whir_db_password
        volumeMounts:
        - name: postgres-vol
          mountPath: /var/lib/postgresql/data
        image: docker.ask4ua.com/whir-db
        ports:
        - containerPort: 5432
          hostPort: 5432
      volumes:
      - name: secrets-vol
        secret:
          secretName: whir-pass
      - name: postgres-vol