- name: Stop logspout
  command: docker stop logspout
  ignore_errors: True

- name: Remove logspout
  command: docker rm logspout
  ignore_errors: True

- name: start logspout
  command: docker run -d --restart always --name logspout -v /var/run/docker.sock:/tmp/docker.sock gliderlabs/logspout syslog://10.5.33.42:5000