 - name: Swapoff
   remote_user: root
   command: swapoff -a

 - name: Disable swap in fstab
   remote_user: root
   command: sed -i '/swap/d' /etc/fstab
   ignore_errors: True

 - name: Remove swap image
   remote_user: root
   command: rm /swap.img
   ignore_errors: True

 - name: Enable Docker
   command: systemctl enable docker
   remote_user: root

 - name: Add the Kubernetes signing key
   remote_user: root
   shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add

 - name: Add the Kubernetes Repo
   remote_user: root
   command: apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"

 - name: Update repos
   remote_user: root
   action: apt update_cache=yes

 - name: Install Kubeadm
   remote_user: root
   apt:
      name: "{{packages}}"
   vars:
      packages:
      - kubeadm

# - name: Init Kubeadm only on Master nodes
#   remote_user: root
#   command: apt install kubeadm
#   when: "master" in inventory_hostname
#    register: results
#    - set_fact:
#        kuberinitstring: "{{ results.stdout | regex_search(regexp,'\\1') }}"
#      vars:
#        regexp: 'kubeadm join \"([^"]+)'
#    - debug:
#        var: kuberinitstring

