 - name: Check Docker installed
   command: docker --version
   ignore_errors: True
   register: docker_status

 - name: Remove older dockers
   remote_user: root
   ignore_errors: True
   command: apt-get remove docker docker-engine docker.io
   when: docker_status is failed

 - name: Apt install required packages
   remote_user: root
   apt:
      name: "{{packages}}"
   vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
   when: docker_status is failed

 - name: Add docker official keys
   remote_user: root
   shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
   when: docker_status is failed

 - name: Install docker repo
   remote_user: root
   shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
   when: docker_status is failed

 - name: Load repo updates including updating docker repo
   remote_user: root
   action: apt update_cache=yes
   register: apt_lock
   ignore_errors: True
   when: docker_status is failed

 - name: Install docker-ce
   apt:
      name: "{{packages}}"
   vars:
      packages:
      - docker-ce
   when: docker_status is failed

 - name: Add docker user to docker group
   remote_user: root
   command: adduser volk docker
   ignore_errors: True
   when: docker_status is failed

# - name: Set local DNS
#   remote_user: root
#   shell: echo 'DOCKER_OPTS=DOCKER_OPTS + " --dns 10.5.33.254"' >> /etc/default/docker
#   ignore_errors: True
#   when: docker_status is failed

