version: "3.1"
services:
        data:
                image: docker.ask4ua.com/whir-data
                volumes:
                        - "data_vol:/data"
                #command: "/bin/bash /app/clone.sh"
                networks:
                        - whirnet
        postgres:
                image: docker.ask4ua.com/whir-db
                ports:
                        - 5432:5432
                volumes:
                        - postgres_vol:/var/lib/postgresql/data
                #secrets:
                #        - whir_db_password
                #        - root_db_password
                environment:
                        - POSTGRES_USER=whir
                        - POSTGRES_DB=whir
                        - POSTGRES_PASSWORD=password
                networks:
                        - whirnet
                deploy:
                        replicas: 1
                        restart_policy:
                                condition: any
        parser:
      # replace username/repo:tag with your name and image details
                image: docker.ask4ua.com/whir-parser
                deploy:
                        replicas: 1
                        restart_policy:
                                condition: any
                                delay: 900s
                        placement:
                                constraints: [node.role == manager]
                #command: "/usr/bin/python3 parser.py"
                volumes:
                        - "data_vol:/data"
                #secrets:
                #        - whir_db_password
                environment:
                        - WHIR_DB_USER=whir
                        - WHIR_DB_NAME=whir
                        - WHIR_DB_PASSWORD=password
                networks:
                        - whirnet
        decomposer:
      # replace username/repo:tag with your name and image details
                image: docker.ask4ua.com/whir-decomposer
                deploy:
                        replicas: 1
                        #resources:
                                #limits:
                                        #cpus: "0.24"
                        restart_policy:
                                condition: any
                                delay: 10s
                #command: "/usr/bin/python3 decomposer.py"
                volumes:
                        - "data_vol:/data"
                #secrets:
                #        - whir_db_password
                environment:
                        - WHIR_DB_USER=whir
                        - WHIR_DB_NAME=whir
                        - WHIR_DB_PASSWORD=password
                networks:
                        - whirnet
secrets:
        whir_db_password:
                external: true
        root_db_password:
                external: true
        
volumes:
        data_vol:
        postgres_vol:
#                driver: local
#                driver_opts:
#                        type: none
#                        device: /mnt/8T/whir/volumes/data_vol
#                        o: bind
networks:
        whirnet:
