version: "3.1"
services:
        postgres:
                image: docker.ask4ua.com/whir-db
                ports:
                        - 5432:5432
                volumes:
                        - postgres_vol:/var/lib/postgresql/data
                secrets:
                        - whir_db_password
                        - root_db_password
                environment:
                        - POSTGRES_USER=whir
                        - POSTGRES_DB=whir
                        - POSTGRES_PASSWORD_FILE=/run/secrets/whir_db_password
                        - POSTGRES_ROOT_PASSWORD_FILE=/run/secrets/root_db_password
                networks:
                        - whirnet
                deploy:
                        placement:
                                constraints: [node.role == manager]
                        replicas: 1
                        restart_policy:
                                condition: any

        data:
                image: docker.ask4ua.com/whir-app
                volumes:
                        - "data_vol:/data"
                command: "/bin/bash /app/clone.sh"
                networks:
                        - whirnet

        parser:
      # replace username/repo:tag with your name and image details
                image: docker.ask4ua.com/whir-app
                deploy:
                        replicas: 1
                        restart_policy:
                                condition: any
                                delay: 900s
                        placement:
                                constraints: [node.role == manager]
                command: "/usr/bin/python3 parser.py"
                volumes:
                        - "data_vol:/data"
                secrets:
                        - whir_db_password
                environment:
                        - WHIR_DB_USER=whir
                        - WHIR_DB_NAME=whir
                        - WHIR_DB_PASSWORD_FILE=/run/secrets/whir_db_password
                        - WHIR_DB_HOST=postgres
                networks:
                        - whirnet
        decomposer:
      # replace username/repo:tag with your name and image details
                image: docker.ask4ua.com/whir-app
                deploy:
                        replicas: 2
                        #resources:
                                #limits:
                                        #cpus: "0.24"
                        restart_policy:
                                condition: any
                                delay: 10s
                command: "/usr/bin/python3 decomposer.py"
                volumes:
                        - "data_vol:/data"
                secrets:
                        - whir_db_password
                environment:
                        - WHIR_DB_USER=whir
                        - WHIR_DB_NAME=whir
                        - WHIR_DB_PASSWORD_FILE=/run/secrets/whir_db_password
                        - WHIR_DB_HOST=postgres
                networks:
                        - whirnet
secrets:
        whir_db_password:
                external: true
        root_db_password:
                external: true
        
volumes:
        postgres_vol:
        data_vol:
networks:
        whirnet:
