version: "3.1"
services:
        mysqldb:
                image: mysql
                ports:
                        - 3306:3306
                volumes:
                        - db_vol:/var/lib/mysql
                secrets:
                        - whir_db_password
                        - root_db_password
                command: --default-authentication-plugin=mysql_native_password
                environment:
                        - MYSQL_USER=whir
                        - MYSQL_DATABASE=whir
                        - MYSQL_PASSWORD_FILE=/run/secrets/whir_db_password
                        - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root_db_password
                networks:
                        - whirnet
                deploy:
                        placement:
                                constraints: [node.role == manager]
                        replicas: 1
                        restart_policy:
                                condition: on-failure
        parser:
      # replace username/repo:tag with your name and image details
                image: whir
                deploy:
                        replicas: 1
                        resources:
                                limits:
                                        cpus: "0.5"
                                        memory: 128M
                        restart_policy:
                                condition: on-failure
                        placement:
                                constraints: [node.role == manager]
                command: "/usr/bin/python3 parser.py"
                volumes:
                        - "data_vol:/data"
                secrets:
                        - whir_db_password
                environment:
                        - WHIR_DB_USER=whir
                        - WHIR_DB_NAME=whir
                        - WHIR_DB_PASSWORD_FILE=/run/secrets/whir_db_password
                        - WHIR_DB_HOST=mysqldb
                networks:
                        - whirnet
        decomposer:
      # replace username/repo:tag with your name and image details
                image: whir
                deploy:
                        replicas: 8
                        resources:
                                limits:
                                        cpus: "0.5"
                                        memory: 1G
                        restart_policy:
                                condition: on-failure
                command: "/usr/bin/python3 decomposer.py"
                volumes:
                        - "data_vol:/data"
                secrets:
                        - whir_db_password
                environment:
                        - WHIR_DB_USER=whir
                        - WHIR_DB_NAME=whir
                        - WHIR_DB_PASSWORD_FILE=/run/secrets/whir_db_password
                        - WHIR_DB_HOST=mysqldb
                networks:
                        - whirnet
secrets:
        whir_db_password:
                external: true
        root_db_password:
                external: true
        
volumes:
        db_vol:
        data_vol:
networks:
        whirnet:
