version: "3.1"
services:
        postgres:
                image: docker.ask4ua.com/whir-db
                ports:
                        - 5432:5432
                volumes:
                        - postgres_vol:/var/lib/postgresql/data
                secrets:
                        - whir_db_password
                        - root_db_password
                environment:
                        - POSTGRES_USER=whir
                        - POSTGRES_DB=whir
                        - POSTGRES_PASSWORD_FILE=/run/secrets/whir_db_password
                        - POSTGRES_ROOT_PASSWORD_FILE=/run/secrets/root_db_password
                networks:
                        - whirnet
                deploy:
                        replicas: 1
                        restart_policy:
                                condition: any
secrets:
        whir_db_password:
                external: true
        root_db_password:
                external: true
        
volumes:
        postgres_vol:
        data_vol:
networks:
        whirnet:
