  - name: shut vhost "{{ item }}" in virsh
    remote_user: root
    become: yes
    become_method: sudo
    command: virsh shutdown {{item}}
    loop: "{{ hostvars['localhost']['groups']['k8s'] }}"
    ignore_errors: True



  - name: copy default image for {{item}} from mnt-4T to SSD
    remote_user: root
    become: yes
    become_method: sudo
    command: rsync -L u1804_64_80G.qcow2 u1804_64_{{item}}.qcow2.wait
    args:
            chdir: /mnt/4T/virsh/images
    loop: "{{ hostvars['localhost']['groups']['k8s_ssd'] }}"

  - name: copy default image for {{item}} from mnt-4T to mnt-8T
    remote_user: root
    become: yes
    become_method: sudo
    command: rsync -L u1804_64_2T.qcow2 /mnt/8T/virsh/images/u1804_64_{{item}}.qcow2.wait
    args:
            chdir: /mnt/4T/virsh/images
    loop: "{{ hostvars['localhost']['groups']['k8s_2T'] }}"


  - name: stop virsh {{item}}
    remote_user: root
    become: yes
    become_method: sudo
    command: virsh destroy {{item}}
    loop: "{{ hostvars['localhost']['groups']['k8s'] }}"
    ignore_errors: True


  - name: remove old image for {{item}} from SSD
    remote_user: root
    become: yes
    become_method: sudo
    command: rm -rf u1804_64_{{item}}.qcow2
    args:
            chdir: /var/lib/virsh
    loop: "{{ hostvars['localhost']['groups']['k8s_ssd'] }}"
    ignore_errors: True

  - name: remove old image for {{item}} from 8T
    remote_user: root
    become: yes
    become_method: sudo
    command: rm -rf u1804_64_{{item}}.qcow2
    args:
            chdir: /mnt/8T/virsh/images/
    loop: "{{ hostvars['localhost']['groups']['k8s_2T'] }}"
    ignore_errors: True


  - name: remove all links for sure {{item}} from SDD
    remote_user: root
    become: yes
    become_method: sudo
    command: rm -rf u1804_64_{{item}}.qcow2
    args:
            chdir: /var/lib/virsh
    loop: "{{ hostvars['localhost']['groups']['k8s'] }}"
    ignore_errors: True


  - name: rename image for {{item}} for SSD
    remote_user: root
    become: yes
    become_method: sudo
    command: mv u1804_64_{{item}}.qcow2.wait u1804_64_{{item}}.qcow2
    args:
            chdir: /var/lib/virsh
    loop: "{{ hostvars['localhost']['groups']['k8s_ssd'] }}"

  - name: rename image for {{item}} for 8T
    remote_user: root
    become: yes
    become_method: sudo
    command: mv u1804_64_{{item}}.qcow2.wait u1804_64_{{item}}.qcow2
    args:
            chdir: /mnt/8T/virsh/images/
    loop: "{{ hostvars['localhost']['groups']['k8s_2T'] }}"


  - name: create links for sure {{item}} from 8T
    remote_user: root
    become: yes
    become_method: sudo
    command: ln -s /mnt/8T/virsh/images/u1804_64_{{item}}.qcow2
    args:
            chdir: /var/lib/virsh
    loop: "{{ hostvars['localhost']['groups']['k8s_2T'] }}"
    ignore_errors: True


  - name: start {{item}}
    remote_user: root
    become: yes
    become_method: sudo
    command: virsh start {{item}}
    loop: "{{ hostvars['localhost']['groups']['k8s'] }}"


  - name: give vhosts time to start
    pause: minutes=1
