  - name: shut vhost "{{ item }}" in virsh
    remote_user: root
    become: yes
    become_method: sudo
    command: virsh shutdown {{item}}
    loop: "{{ hostvars['localhost']['groups']['k8s'] }}"
    ignore_errors: True

  - name: copy default image for {{item}} from mnt-4T to SSD
    remote_user: root
    become: yes
    become_method: sudo
    command: rsync -auv u1804_64_80G.qcow2 /var/lib/virsh/u1804_64_{{item}}.qcow2.wait
    args:
            chdir: /mnt/4T/virsh/images
    loop: "{{ hostvars['localhost']['groups']['k8s'] }}"

  - name: stop virsh {{item}}
    remote_user: root
    become: yes
    become_method: sudo
    command: virsh destroy {{item}}
    loop: "{{ hostvars['localhost']['groups']['k8s'] }}"
    ignore_errors: True

  - name: remove old image for {{item}}
    remote_user: root
    become: yes
    become_method: sudo
    command: rm -rf u1804_64_{{item}}.qcow2
    args:
            chdir: /var/lib/virsh
    loop: "{{ hostvars['localhost']['groups']['k8s'] }}"
    ignore_errors: True

  - name: rename image for {{item}}
    remote_user: root
    become: yes
    become_method: sudo
    command: mv u1804_64_{{item}}.qcow2.wait u1804_64_{{item}}.qcow2
    args:
            chdir: /var/lib/virsh
    loop: "{{ hostvars['localhost']['groups']['k8s'] }}"

  - name: start {{item}}
    remote_user: root
    become: yes
    become_method: sudo
    command: virsh start {{item}}
    loop: "{{ hostvars['localhost']['groups']['k8s'] }}"


  - name: give vhosts time to start
    pause: minutes=1
